import asyncio
from database import db
WORDS = [

("man", "мужчина", "en", "people", "A1"),
("woman", "женщина", "en", "people", "A1"),
("boy", "мальчик", "en", "people", "A1"),
("girl", "девочка", "en", "people", "A1"),
("child", "ребёнок", "en", "people", "A1"),
("baby", "малыш", "en", "people", "A1"),
("father", "отец", "en", "people", "A1"),
("mother", "мать", "en", "people", "A1"),
("son", "сын", "en", "people", "A1"),
("daughter", "дочь", "en", "people", "A1"),

("brother", "брат", "en", "people", "A1"),
("sister", "сестра", "en", "people", "A1"),
("family", "семья", "en", "people", "A1"),
("friend", "друг", "en", "people", "A1"),
("person", "человек", "en", "people", "A1"),
("people", "люди", "en", "people", "A1"),
("name", "имя", "en", "people", "A1"),
("man", "мужчина", "en", "people", "A1"),
("wife", "жена", "en", "people", "A1"),
("husband", "муж", "en", "people", "A1"),

("teacher", "учитель", "en", "people", "A1"),
("student", "ученик", "en", "people", "A1"),
("doctor", "врач", "en", "people", "A1"),
("nurse", "медсестра", "en", "people", "A1"),
("driver", "водитель", "en", "people", "A1"),
("worker", "рабочий", "en", "people", "A1"),
("farmer", "фермер", "en", "people", "A1"),
("cook", "повар", "en", "people", "A1"),
("police", "полиция", "en", "people", "A1"),
("boss", "начальник", "en", "people", "A1"),

("friend", "друг", "en", "people", "A1"),
("neighbor", "сосед", "en", "people", "A1"),
("guest", "гость", "en", "people", "A1"),
("customer", "клиент", "en", "people", "A1"),
("child", "ребёнок", "en", "people", "A1"),
("student", "студент", "en", "people", "A1"),
("classmate", "одноклассник", "en", "people", "A1"),
("partner", "партнёр", "en", "people", "A1"),
("leader", "лидер", "en", "people", "A1"),
("king", "король", "en", "people", "A1"),

("queen", "королева", "en", "people", "A1"),
("boyfriend", "парень", "en", "people", "A1"),
("girlfriend", "девушка", "en", "people", "A1"),
("parent", "родитель", "en", "people", "A1"),
("grandfather", "дедушка", "en", "people", "A1"),
("grandmother", "бабушка", "en", "people", "A1"),
("uncle", "дядя", "en", "people", "A1"),
("aunt", "тётя", "en", "people", "A1"),
("cousin", "двоюродный брат/сестра", "en", "people", "A1"),
("relative", "родственник", "en", "people", "A1"),

("adult", "взрослый", "en", "people", "A1"),
("teenager", "подросток", "en", "people", "A1"),
("old", "старый", "en", "people", "A1"),
("young", "молодой", "en", "people", "A1"),
("married", "женатый/замужем", "en", "people", "A1"),
("single", "одинокий/не женат", "en", "people", "A1"),
("rich", "богатый", "en", "people", "A1"),
("poor", "бедный", "en", "people", "A1"),
("happy", "счастливый", "en", "people", "A1"),
("sad", "грустный", "en", "people", "A1"),

("kind", "добрый", "en", "people", "A1"),
("nice", "приятный", "en", "people", "A1"),
("funny", "смешной", "en", "people", "A1"),
("strong", "сильный", "en", "people", "A1"),
("weak", "слабый", "en", "people", "A1"),
("tall", "высокий", "en", "people", "A1"),
("short", "низкий", "en", "people", "A1"),
("beautiful", "красивый", "en", "people", "A1"),
("smart", "умный", "en", "people", "A1"),
("silly", "глупый", "en", "people", "A1"),

("baby", "младенец", "en", "people", "A1"),
("man", "мужчина", "en", "people", "A1"),
("woman", "женщина", "en", "people", "A1"),
("boy", "мальчик", "en", "people", "A1"),
("girl", "девочка", "en", "people", "A1"),
("friendship", "дружба", "en", "people", "A1"),
("team", "команда", "en", "people", "A1"),
("group", "группа", "en", "people", "A1"),
("member", "член группы", "en", "people", "A1"),
("hero", "герой", "en", "people", "A1"),

("artist", "художник", "en", "people", "A1"),
("actor", "актёр", "en", "people", "A1"),
("singer", "певец", "en", "people", "A1"),
("writer", "писатель", "en", "people", "A1"),
("player", "игрок", "en", "people", "A1"),
("seller", "продавец", "en", "people", "A1"),
("waiter", "официант", "en", "people", "A1"),
("manager", "менеджер", "en", "people", "A1"),
("engineer", "инженер", "en", "people", "A1"),
("programmer", "программист", "en", "people", "A1"),
("house", "дом", "en", "home", "A1"),
("home", "дом/жильё", "en", "home", "A1"),
("room", "комната", "en", "home", "A1"),
("door", "дверь", "en", "home", "A1"),
("window", "окно", "en", "home", "A1"),
("wall", "стена", "en", "home", "A1"),
("floor", "пол", "en", "home", "A1"),
("roof", "крыша", "en", "home", "A1"),
("ceiling", "потолок", "en", "home", "A1"),
("garden", "сад", "en", "home", "A1"),

("kitchen", "кухня", "en", "home", "A1"),
("bedroom", "спальня", "en", "home", "A1"),
("bathroom", "ванная", "en", "home", "A1"),
("living room", "гостиная", "en", "home", "A1"),
("garage", "гараж", "en", "home", "A1"),
("balcony", "балкон", "en", "home", "A1"),
("stairs", "лестница", "en", "home", "A1"),
("table", "стол", "en", "home", "A1"),
("chair", "стул", "en", "home", "A1"),
("bed", "кровать", "en", "home", "A1"),

("sofa", "диван", "en", "home", "A1"),
("desk", "рабочий стол", "en", "home", "A1"),
("shelf", "полка", "en", "home", "A1"),
("box", "коробка", "en", "home", "A1"),
("cupboard", "шкаф", "en", "home", "A1"),
("closet", "гардероб", "en", "home", "A1"),
("mirror", "зеркало", "en", "home", "A1"),
("lamp", "лампа", "en", "home", "A1"),
("light", "свет", "en", "home", "A1"),
("key", "ключ", "en", "home", "A1"),

("lock", "замок", "en", "home", "A1"),
("clock", "часы", "en", "home", "A1"),
("picture", "картина", "en", "home", "A1"),
("photo", "фото", "en", "home", "A1"),
("book", "книга", "en", "home", "A1"),
("paper", "бумага", "en", "home", "A1"),
("pen", "ручка", "en", "home", "A1"),
("pencil", "карандаш", "en", "home", "A1"),
("computer", "компьютер", "en", "home", "A1"),
("phone", "телефон", "en", "home", "A1"),

("television", "телевизор", "en", "home", "A1"),
("radio", "радио", "en", "home", "A1"),
("camera", "камера", "en", "home", "A1"),
("bag", "сумка", "en", "home", "A1"),
("clothes", "одежда", "en", "home", "A1"),
("shirt", "рубашка", "en", "home", "A1"),
("shoe", "обувь", "en", "home", "A1"),
("sock", "носок", "en", "home", "A1"),
("coat", "пальто", "en", "home", "A1"),
("hat", "шапка", "en", "home", "A1"),

("towel", "полотенце", "en", "home", "A1"),
("soap", "мыло", "en", "home", "A1"),
("brush", "щётка", "en", "home", "A1"),
("toothbrush", "зубная щётка", "en", "home", "A1"),
("toothpaste", "зубная паста", "en", "home", "A1"),
("water", "вода", "en", "home", "A1"),
("bath", "ванна", "en", "home", "A1"),
("shower", "душ", "en", "home", "A1"),
("toilet", "туалет", "en", "home", "A1"),
("clean", "чистый", "en", "home", "A1"),

("dirty", "грязный", "en", "home", "A1"),
("open", "открытый", "en", "home", "A1"),
("closed", "закрытый", "en", "home", "A1"),
("big", "большой", "en", "home", "A1"),
("small", "маленький", "en", "home", "A1"),
("new", "новый", "en", "home", "A1"),
("old", "старый", "en", "home", "A1"),
("hot", "горячий", "en", "home", "A1"),
("cold", "холодный", "en", "home", "A1"),
("floor", "этаж/пол", "en", "home", "A1"),

("key", "ключ", "en", "home", "A1"),
("doorbell", "звонок", "en", "home", "A1"),
("housework", "домашняя работа", "en", "home", "A1"),
("cook", "готовить", "en", "home", "A1"),
("wash", "мыть", "en", "home", "A1"),
("clean", "убирать", "en", "home", "A1"),
("sleep", "спать", "en", "home", "A1"),
("sit", "сидеть", "en", "home", "A1"),
("stand", "стоять", "en", "home", "A1"),
("live", "жить", "en", "home", "A1"),

("move", "двигаться", "en", "home", "A1"),
("stay", "оставаться", "en", "home", "A1"),
("build", "строить", "en", "home", "A1"),
("repair", "чинить", "en", "home", "A1"),
("paint", "красить", "en", "home", "A1"),
("door", "дверь", "en", "home", "A1"),
("window", "окно", "en", "home", "A1"),
("kettle", "чайник", "en", "home", "A1"),
("plate", "тарелка", "en", "home", "A1"),
("glass", "стакан", "en", "home", "A1"),
("food", "еда", "en", "food", "A1"),
("meal", "приём пищи", "en", "food", "A1"),
("breakfast", "завтрак", "en", "food", "A1"),
("lunch", "обед", "en", "food", "A1"),
("dinner", "ужин", "en", "food", "A1"),
("bread", "хлеб", "en", "food", "A1"),
("rice", "рис", "en", "food", "A1"),
("pasta", "макароны", "en", "food", "A1"),
("soup", "суп", "en", "food", "A1"),
("meat", "мясо", "en", "food", "A1"),

("chicken", "курица", "en", "food", "A1"),
("fish", "рыба", "en", "food", "A1"),
("egg", "яйцо", "en", "food", "A1"),
("cheese", "сыр", "en", "food", "A1"),
("butter", "масло", "en", "food", "A1"),
("milk", "молоко", "en", "food", "A1"),
("yogurt", "йогурт", "en", "food", "A1"),
("cream", "сливки", "en", "food", "A1"),
("salt", "соль", "en", "food", "A1"),
("sugar", "сахар", "en", "food", "A1"),

("pepper", "перец", "en", "food", "A1"),
("oil", "масло", "en", "food", "A1"),
("cake", "торт", "en", "food", "A1"),
("cookie", "печенье", "en", "food", "A1"),
("chocolate", "шоколад", "en", "food", "A1"),
("candy", "конфета", "en", "food", "A1"),
("ice cream", "мороженое", "en", "food", "A1"),
("sandwich", "бутерброд", "en", "food", "A1"),
("pizza", "пицца", "en", "food", "A1"),
("burger", "бургер", "en", "food", "A1"),

("apple", "яблоко", "en", "food", "A1"),
("banana", "банан", "en", "food", "A1"),
("orange", "апельсин", "en", "food", "A1"),
("lemon", "лимон", "en", "food", "A1"),
("grape", "виноград", "en", "food", "A1"),
("pear", "груша", "en", "food", "A1"),
("peach", "персик", "en", "food", "A1"),
("strawberry", "клубника", "en", "food", "A1"),
("watermelon", "арбуз", "en", "food", "A1"),
("melon", "дыня", "en", "food", "A1"),

("potato", "картофель", "en", "food", "A1"),
("tomato", "помидор", "en", "food", "A1"),
("onion", "лук", "en", "food", "A1"),
("carrot", "морковь", "en", "food", "A1"),
("cucumber", "огурец", "en", "food", "A1"),
("salad", "салат", "en", "food", "A1"),
("bean", "фасоль", "en", "food", "A1"),
("corn", "кукуруза", "en", "food", "A1"),
("pea", "горох", "en", "food", "A1"),
("mushroom", "гриб", "en", "food", "A1"),

("tea", "чай", "en", "drink", "A1"),
("coffee", "кофе", "en", "drink", "A1"),
("water", "вода", "en", "drink", "A1"),
("juice", "сок", "en", "drink", "A1"),
("drink", "напиток", "en", "drink", "A1"),
("beer", "пиво", "en", "drink", "A1"),
("wine", "вино", "en", "drink", "A1"),
("bottle", "бутылка", "en", "drink", "A1"),
("cup", "чашка", "en", "drink", "A1"),
("glass", "стакан", "en", "drink", "A1"),

("plate", "тарелка", "en", "food", "A1"),
("bowl", "миска", "en", "food", "A1"),
("fork", "вилка", "en", "food", "A1"),
("knife", "нож", "en", "food", "A1"),
("spoon", "ложка", "en", "food", "A1"),
("cook", "готовить", "en", "food", "A1"),
("eat", "есть", "en", "food", "A1"),
("taste", "вкус", "en", "food", "A1"),
("sweet", "сладкий", "en", "food", "A1"),
("salty", "солёный", "en", "food", "A1"),

("hot", "горячий", "en", "food", "A1"),
("cold", "холодный", "en", "food", "A1"),
("fresh", "свежий", "en", "food", "A1"),
("good", "хороший", "en", "food", "A1"),
("bad", "плохой", "en", "food", "A1"),
("hungry", "голодный", "en", "food", "A1"),
("thirsty", "хочется пить", "en", "food", "A1"),
("full", "сытый", "en", "food", "A1"),
("buy", "покупать", "en", "food", "A1"),
("sell", "продавать", "en", "food", "A1"),
("animal", "животное", "en", "animals", "A1"),
("dog", "собака", "en", "animals", "A1"),
("cat", "кошка", "en", "animals", "A1"),
("bird", "птица", "en", "animals", "A1"),
("fish", "рыба", "en", "animals", "A1"),
("horse", "лошадь", "en", "animals", "A1"),
("cow", "корова", "en", "animals", "A1"),
("pig", "свинья", "en", "animals", "A1"),
("sheep", "овца", "en", "animals", "A1"),
("goat", "коза", "en", "animals", "A1"),

("chicken", "курица", "en", "animals", "A1"),
("duck", "утка", "en", "animals", "A1"),
("rabbit", "кролик", "en", "animals", "A1"),
("mouse", "мышь", "en", "animals", "A1"),
("rat", "крыса", "en", "animals", "A1"),
("frog", "лягушка", "en", "animals", "A1"),
("snake", "змея", "en", "animals", "A1"),
("turtle", "черепаха", "en", "animals", "A1"),
("lion", "лев", "en", "animals", "A1"),
("tiger", "тигр", "en", "animals", "A1"),

("elephant", "слон", "en", "animals", "A1"),
("monkey", "обезьяна", "en", "animals", "A1"),
("bear", "медведь", "en", "animals", "A1"),
("wolf", "волк", "en", "animals", "A1"),
("fox", "лиса", "en", "animals", "A1"),
("deer", "олень", "en", "animals", "A1"),
("giraffe", "жираф", "en", "animals", "A1"),
("zebra", "зебра", "en", "animals", "A1"),
("kangaroo", "кенгуру", "en", "animals", "A1"),
("panda", "панда", "en", "animals", "A1"),

("camel", "верблюд", "en", "animals", "A1"),
("leopard", "леопард", "en", "animals", "A1"),
("cheetah", "гепард", "en", "animals", "A1"),
("shark", "акула", "en", "animals", "A1"),
("whale", "кит", "en", "animals", "A1"),
("dolphin", "дельфин", "en", "animals", "A1"),
("octopus", "осьминог", "en", "animals", "A1"),
("crab", "краб", "en", "animals", "A1"),
("snake", "змея", "en", "animals", "A1"),
("lizard", "ящерица", "en", "animals", "A1"),

("butterfly", "бабочка", "en", "animals", "A1"),
("bee", "пчела", "en", "animals", "A1"),
("ant", "муравей", "en", "animals", "A1"),
("fly", "муха", "en", "animals", "A1"),
("spider", "паук", "en", "animals", "A1"),
("worm", "червь", "en", "animals", "A1"),
("insect", "насекомое", "en", "animals", "A1"),
("frog", "лягушка", "en", "animals", "A1"),
("snake", "змея", "en", "animals", "A1"),
("bird", "птица", "en", "animals", "A1"),

("tail", "хвост", "en", "animals", "A1"),
("leg", "нога", "en", "animals", "A1"),
("wing", "крыло", "en", "animals", "A1"),
("head", "голова", "en", "animals", "A1"),
("eye", "глаз", "en", "animals", "A1"),
("ear", "ухо", "en", "animals", "A1"),
("nose", "нос", "en", "animals", "A1"),
("mouth", "рот", "en", "animals", "A1"),
("tooth", "зуб", "en", "animals", "A1"),
("fur", "шерсть", "en", "animals", "A1"),

("wild", "дикий", "en", "animals", "A1"),
("pet", "домашний питомец", "en", "animals", "A1"),
("farm", "ферма", "en", "animals", "A1"),
("zoo", "зоопарк", "en", "animals", "A1"),
("feed", "кормить", "en", "animals", "A1"),
("walk", "гулять", "en", "animals", "A1"),
("run", "бегать", "en", "animals", "A1"),
("jump", "прыгать", "en", "animals", "A1"),
("sleep", "спать", "en", "animals", "A1"),
("eat", "есть", "en", "animals", "A1"),

("big", "большой", "en", "animals", "A1"),
("small", "маленький", "en", "animals", "A1"),
("fast", "быстрый", "en", "animals", "A1"),
("slow", "медленный", "en", "animals", "A1"),
("strong", "сильный", "en", "animals", "A1"),
("dangerous", "опасный", "en", "animals", "A1"),
("friendly", "дружелюбный", "en", "animals", "A1"),
("cute", "милый", "en", "animals", "A1"),
("young", "молодой", "en", "animals", "A1"),
("old", "старый", "en", "animals", "A1"),

("baby", "детёныш", "en", "animals", "A1"),
("mother", "мама", "en", "animals", "A1"),
("father", "папа", "en", "animals", "A1"),
("home", "дом", "en", "animals", "A1"),
("forest", "лес", "en", "animals", "A1"),
("river", "река", "en", "animals", "A1"),
("sea", "море", "en", "animals", "A1"),
("tree", "дерево", "en", "animals", "A1"),
("grass", "трава", "en", "animals", "A1"),
("food", "еда", "en", "animals", "A1"),
("car", "машина", "en", "transport", "A1"),
("bus", "автобус", "en", "transport", "A1"),
("train", "поезд", "en", "transport", "A1"),
("plane", "самолёт", "en", "transport", "A1"),
("bike", "велосипед", "en", "transport", "A1"),
("bicycle", "велосипед", "en", "transport", "A1"),
("motorcycle", "мотоцикл", "en", "transport", "A1"),
("taxi", "такси", "en", "transport", "A1"),
("truck", "грузовик", "en", "transport", "A1"),
("boat", "лодка", "en", "transport", "A1"),
("ship", "корабль", "en", "transport", "A1"),
("subway", "метро", "en", "transport", "A1"),
("station", "станция", "en", "transport", "A1"),
("airport", "аэропорт", "en", "transport", "A1"),
("road", "дорога", "en", "transport", "A1"),
("street", "улица", "en", "city", "A1"),
("bridge", "мост", "en", "city", "A1"),
("traffic", "движение транспорта", "en", "city", "A1"),
("map", "карта", "en", "city", "A1"),
("ticket", "билет", "en", "transport", "A1"),

("city", "город", "en", "city", "A1"),
("town", "городок", "en", "city", "A1"),
("village", "деревня", "en", "city", "A1"),
("country", "страна", "en", "city", "A1"),
("capital", "столица", "en", "city", "A1"),
("building", "здание", "en", "city", "A1"),
("house", "дом", "en", "city", "A1"),
("school", "школа", "en", "places", "A1"),
("hospital", "больница", "en", "places", "A1"),
("bank", "банк", "en", "places", "A1"),
("shop", "магазин", "en", "places", "A1"),
("market", "рынок", "en", "places", "A1"),
("restaurant", "ресторан", "en", "places", "A1"),
("cafe", "кафе", "en", "places", "A1"),
("hotel", "отель", "en", "places", "A1"),
("park", "парк", "en", "places", "A1"),
("library", "библиотека", "en", "places", "A1"),
("museum", "музей", "en", "places", "A1"),
("cinema", "кинотеатр", "en", "places", "A1"),
("office", "офис", "en", "places", "A1"),

("company", "компания", "en", "work", "A1"),
("factory", "фабрика", "en", "work", "A1"),
("farm", "ферма", "en", "places", "A1"),
("church", "церковь", "en", "places", "A1"),
("store", "магазин", "en", "places", "A1"),
("supermarket", "супермаркет", "en", "places", "A1"),
("pharmacy", "аптека", "en", "places", "A1"),
("post office", "почта", "en", "places", "A1"),
("police station", "полицейский участок", "en", "places", "A1"),
("bus stop", "автобусная остановка", "en", "transport", "A1"),

("left", "лево", "en", "city", "A1"),
("right", "право", "en", "city", "A1"),
("straight", "прямо", "en", "city", "A1"),
("near", "рядом", "en", "city", "A1"),
("far", "далеко", "en", "city", "A1"),
("inside", "внутри", "en", "city", "A1"),
("outside", "снаружи", "en", "city", "A1"),
("here", "здесь", "en", "city", "A1"),
("there", "там", "en", "city", "A1"),
("where", "где", "en", "city", "A1"),

("go", "идти", "en", "verbs", "A1"),
("come", "приходить", "en", "verbs", "A1"),
("drive", "водить", "en", "verbs", "A1"),
("fly", "летать", "en", "verbs", "A1"),
("stop", "останавливаться", "en", "verbs", "A1"),
("start", "начинать", "en", "verbs", "A1"),
("turn", "поворачивать", "en", "verbs", "A1"),
("wait", "ждать", "en", "verbs", "A1"),
("arrive", "прибывать", "en", "verbs", "A1"),
("leave", "уезжать", "en", "verbs", "A1"),
("school", "школа", "en", "school", "A1"),
("class", "класс", "en", "school", "A1"),
("lesson", "урок", "en", "school", "A1"),
("teacher", "учитель", "en", "school", "A1"),
("student", "ученик", "en", "school", "A1"),
("book", "книга", "en", "school", "A1"),
("notebook", "тетрадь", "en", "school", "A1"),
("pen", "ручка", "en", "school", "A1"),
("pencil", "карандаш", "en", "school", "A1"),
("paper", "бумага", "en", "school", "A1"),

("question", "вопрос", "en", "school", "A1"),
("answer", "ответ", "en", "school", "A1"),
("test", "тест", "en", "school", "A1"),
("exam", "экзамен", "en", "school", "A1"),
("homework", "домашняя работа", "en", "school", "A1"),
("subject", "предмет", "en", "school", "A1"),
("math", "математика", "en", "school", "A1"),
("English", "английский язык", "en", "school", "A1"),
("language", "язык", "en", "school", "A1"),
("word", "слово", "en", "school", "A1"),


# WORK A1

("work", "работа", "en", "work", "A1"),
("job", "работа/должность", "en", "work", "A1"),
("office", "офис", "en", "work", "A1"),
("company", "компания", "en", "work", "A1"),
("boss", "начальник", "en", "work", "A1"),
("worker", "работник", "en", "work", "A1"),
("manager", "менеджер", "en", "work", "A1"),
("doctor", "врач", "en", "work", "A1"),
("teacher", "учитель", "en", "work", "A1"),
("driver", "водитель", "en", "work", "A1"),

("engineer", "инженер", "en", "work", "A1"),
("programmer", "программист", "en", "work", "A1"),
("artist", "художник", "en", "work", "A1"),
("actor", "актёр", "en", "work", "A1"),
("cook", "повар", "en", "work", "A1"),
("waiter", "официант", "en", "work", "A1"),
("seller", "продавец", "en", "work", "A1"),
("money", "деньги", "en", "work", "A1"),
("pay", "платить", "en", "work", "A1"),
("salary", "зарплата", "en", "work", "A1"),


# DAILY ROUTINE A1

("wake up", "просыпаться", "en", "daily", "A1"),
("get up", "вставать", "en", "daily", "A1"),
("wash", "мыть", "en", "daily", "A1"),
("brush", "чистить", "en", "daily", "A1"),
("dress", "одеваться", "en", "daily", "A1"),
("eat", "есть", "en", "daily", "A1"),
("drink", "пить", "en", "daily", "A1"),
("cook", "готовить", "en", "daily", "A1"),
("go", "идти", "en", "daily", "A1"),
("come", "приходить", "en", "daily", "A1"),

("sleep", "спать", "en", "daily", "A1"),
("read", "читать", "en", "daily", "A1"),
("write", "писать", "en", "daily", "A1"),
("listen", "слушать", "en", "daily", "A1"),
("watch", "смотреть", "en", "daily", "A1"),
("play", "играть", "en", "daily", "A1"),
("walk", "гулять", "en", "daily", "A1"),
("run", "бегать", "en", "daily", "A1"),
("buy", "покупать", "en", "daily", "A1"),
("sell", "продавать", "en", "daily", "A1"),

("open", "открывать", "en", "daily", "A1"),
("close", "закрывать", "en", "daily", "A1"),
("start", "начинать", "en", "daily", "A1"),
("finish", "заканчивать", "en", "daily", "A1"),
("help", "помогать", "en", "daily", "A1"),
("call", "звонить", "en", "daily", "A1"),
("meet", "встречать", "en", "daily", "A1"),
("talk", "говорить", "en", "daily", "A1"),
("move", "двигаться", "en", "daily", "A1"),
("stay", "оставаться", "en", "daily", "A1"),
# TIME A1

("time", "время", "en", "time", "A1"),
("day", "день", "en", "time", "A1"),
("week", "неделя", "en", "time", "A1"),
("month", "месяц", "en", "time", "A1"),
("year", "год", "en", "time", "A1"),
("today", "сегодня", "en", "time", "A1"),
("tomorrow", "завтра", "en", "time", "A1"),
("yesterday", "вчера", "en", "time", "A1"),
("morning", "утро", "en", "time", "A1"),
("afternoon", "день", "en", "time", "A1"),

("evening", "вечер", "en", "time", "A1"),
("night", "ночь", "en", "time", "A1"),
("hour", "час", "en", "time", "A1"),
("minute", "минута", "en", "time", "A1"),
("second", "секунда", "en", "time", "A1"),
("early", "рано", "en", "time", "A1"),
("late", "поздно", "en", "time", "A1"),
("now", "сейчас", "en", "time", "A1"),
("before", "до", "en", "time", "A1"),
("after", "после", "en", "time", "A1"),


# NUMBERS A1

("one", "один", "en", "numbers", "A1"),
("two", "два", "en", "numbers", "A1"),
("three", "три", "en", "numbers", "A1"),
("four", "четыре", "en", "numbers", "A1"),
("five", "пять", "en", "numbers", "A1"),
("six", "шесть", "en", "numbers", "A1"),
("seven", "семь", "en", "numbers", "A1"),
("eight", "восемь", "en", "numbers", "A1"),
("nine", "девять", "en", "numbers", "A1"),
("ten", "десять", "en", "numbers", "A1"),

("eleven", "одиннадцать", "en", "numbers", "A1"),
("twelve", "двенадцать", "en", "numbers", "A1"),
("thirteen", "тринадцать", "en", "numbers", "A1"),
("fourteen", "четырнадцать", "en", "numbers", "A1"),
("fifteen", "пятнадцать", "en", "numbers", "A1"),
("twenty", "двадцать", "en", "numbers", "A1"),
("thirty", "тридцать", "en", "numbers", "A1"),
("hundred", "сто", "en", "numbers", "A1"),
("first", "первый", "en", "numbers", "A1"),
("second", "второй", "en", "numbers", "A1"),


# COLORS A1

("color", "цвет", "en", "colors", "A1"),
("red", "красный", "en", "colors", "A1"),
("blue", "синий", "en", "colors", "A1"),
("green", "зелёный", "en", "colors", "A1"),
("yellow", "жёлтый", "en", "colors", "A1"),
("black", "чёрный", "en", "colors", "A1"),
("white", "белый", "en", "colors", "A1"),
("orange", "оранжевый", "en", "colors", "A1"),
("pink", "розовый", "en", "colors", "A1"),
("brown", "коричневый", "en", "colors", "A1"),

("gray", "серый", "en", "colors", "A1"),
("purple", "фиолетовый", "en", "colors", "A1"),
("dark", "тёмный", "en", "colors", "A1"),
("light", "светлый", "en", "colors", "A1"),


# CLOTHES A1

("clothes", "одежда", "en", "clothes", "A1"),
("shirt", "рубашка", "en", "clothes", "A1"),
("t-shirt", "футболка", "en", "clothes", "A1"),
("trousers", "брюки", "en", "clothes", "A1"),
("jeans", "джинсы", "en", "clothes", "A1"),
("dress", "платье", "en", "clothes", "A1"),
("skirt", "юбка", "en", "clothes", "A1"),
("jacket", "куртка", "en", "clothes", "A1"),
("coat", "пальто", "en", "clothes", "A1"),
("shoe", "ботинок", "en", "clothes", "A1"),

("sock", "носок", "en", "clothes", "A1"),
("hat", "шапка", "en", "clothes", "A1"),
("cap", "кепка", "en", "clothes", "A1"),
("glove", "перчатка", "en", "clothes", "A1"),
("scarf", "шарф", "en", "clothes", "A1"),
("belt", "ремень", "en", "clothes", "A1"),
("pocket", "карман", "en", "clothes", "A1"),
("wear", "носить", "en", "clothes", "A1"),
("put on", "надеть", "en", "clothes", "A1"),
("take off", "снять", "en", "clothes", "A1"),
# BODY A1

("body", "тело", "en", "body", "A1"),
("head", "голова", "en", "body", "A1"),
("face", "лицо", "en", "body", "A1"),
("hair", "волосы", "en", "body", "A1"),
("eye", "глаз", "en", "body", "A1"),
("ear", "ухо", "en", "body", "A1"),
("nose", "нос", "en", "body", "A1"),
("mouth", "рот", "en", "body", "A1"),
("tooth", "зуб", "en", "body", "A1"),
("neck", "шея", "en", "body", "A1"),

("arm", "рука", "en", "body", "A1"),
("hand", "кисть руки", "en", "body", "A1"),
("finger", "палец", "en", "body", "A1"),
("leg", "нога", "en", "body", "A1"),
("foot", "ступня", "en", "body", "A1"),
("back", "спина", "en", "body", "A1"),
("heart", "сердце", "en", "body", "A1"),
("skin", "кожа", "en", "body", "A1"),
("blood", "кровь", "en", "body", "A1"),
("bone", "кость", "en", "body", "A1"),


# HEALTH A1

("health", "здоровье", "en", "health", "A1"),
("sick", "больной", "en", "health", "A1"),
("healthy", "здоровый", "en", "health", "A1"),
("doctor", "врач", "en", "health", "A1"),
("hospital", "больница", "en", "health", "A1"),
("medicine", "лекарство", "en", "health", "A1"),
("pain", "боль", "en", "health", "A1"),
("fever", "температура", "en", "health", "A1"),
("cold", "простуда", "en", "health", "A1"),
("cough", "кашель", "en", "health", "A1"),

("sleep", "сон", "en", "health", "A1"),
("rest", "отдых", "en", "health", "A1"),
("exercise", "упражнение", "en", "health", "A1"),
("walk", "ходить", "en", "health", "A1"),
("run", "бегать", "en", "health", "A1"),
("strong", "сильный", "en", "health", "A1"),
("weak", "слабый", "en", "health", "A1"),
("hurt", "болеть", "en", "health", "A1"),
("help", "помощь", "en", "health", "A1"),
("emergency", "чрезвычайная ситуация", "en", "health", "A1"),


# NATURE A1

("nature", "природа", "en", "nature", "A1"),
("tree", "дерево", "en", "nature", "A1"),
("flower", "цветок", "en", "nature", "A1"),
("grass", "трава", "en", "nature", "A1"),
("forest", "лес", "en", "nature", "A1"),
("river", "река", "en", "nature", "A1"),
("lake", "озеро", "en", "nature", "A1"),
("sea", "море", "en", "nature", "A1"),
("ocean", "океан", "en", "nature", "A1"),
("mountain", "гора", "en", "nature", "A1"),

("hill", "холм", "en", "nature", "A1"),
("island", "остров", "en", "nature", "A1"),
("stone", "камень", "en", "nature", "A1"),
("sand", "песок", "en", "nature", "A1"),
("earth", "земля", "en", "nature", "A1"),
("sky", "небо", "en", "nature", "A1"),
("sun", "солнце", "en", "nature", "A1"),
("moon", "луна", "en", "nature", "A1"),
("star", "звезда", "en", "nature", "A1"),
("fire", "огонь", "en", "nature", "A1"),


# WEATHER A1

("weather", "погода", "en", "weather", "A1"),
("sunny", "солнечный", "en", "weather", "A1"),
("rain", "дождь", "en", "weather", "A1"),
("snow", "снег", "en", "weather", "A1"),
("wind", "ветер", "en", "weather", "A1"),
("cloud", "облако", "en", "weather", "A1"),
("storm", "буря", "en", "weather", "A1"),
("hot", "жаркий", "en", "weather", "A1"),
("cold", "холодный", "en", "weather", "A1"),
("warm", "тёплый", "en", "weather", "A1"),

("cool", "прохладный", "en", "weather", "A1"),
("dry", "сухой", "en", "weather", "A1"),
("wet", "мокрый", "en", "weather", "A1"),
("season", "время года", "en", "weather", "A1"),
("spring", "весна", "en", "weather", "A1"),
("summer", "лето", "en", "weather", "A1"),
("autumn", "осень", "en", "weather", "A1"),
("winter", "зима", "en", "weather", "A1"),
("temperature", "температура", "en", "weather", "A1"),
("degree", "градус", "en", "weather", "A1"),
# TRAVEL A1

("travel", "путешествие", "en", "travel", "A1"),
("trip", "поездка", "en", "travel", "A1"),
("holiday", "отпуск", "en", "travel", "A1"),
("vacation", "каникулы", "en", "travel", "A1"),
("tour", "тур", "en", "travel", "A1"),
("hotel", "отель", "en", "travel", "A1"),
("room", "комната", "en", "travel", "A1"),
("key", "ключ", "en", "travel", "A1"),
("ticket", "билет", "en", "travel", "A1"),
("passport", "паспорт", "en", "travel", "A1"),

("map", "карта", "en", "travel", "A1"),
("country", "страна", "en", "travel", "A1"),
("city", "город", "en", "travel", "A1"),
("village", "деревня", "en", "travel", "A1"),
("street", "улица", "en", "travel", "A1"),
("road", "дорога", "en", "travel", "A1"),
("station", "станция", "en", "travel", "A1"),
("airport", "аэропорт", "en", "travel", "A1"),
("train", "поезд", "en", "travel", "A1"),
("plane", "самолёт", "en", "travel", "A1"),

("bus", "автобус", "en", "transport", "A1"),
("car", "машина", "en", "transport", "A1"),
("taxi", "такси", "en", "transport", "A1"),
("bike", "велосипед", "en", "transport", "A1"),
("boat", "лодка", "en", "transport", "A1"),
("ship", "корабль", "en", "transport", "A1"),
("drive", "водить", "en", "transport", "A1"),
("ride", "ехать", "en", "transport", "A1"),
("fly", "лететь", "en", "transport", "A1"),
("stop", "остановка", "en", "transport", "A1"),


# SHOPPING A1

("shop", "магазин", "en", "shopping", "A1"),
("store", "магазин", "en", "shopping", "A1"),
("market", "рынок", "en", "shopping", "A1"),
("buy", "покупать", "en", "shopping", "A1"),
("sell", "продавать", "en", "shopping", "A1"),
("price", "цена", "en", "shopping", "A1"),
("cost", "стоимость", "en", "shopping", "A1"),
("cheap", "дешёвый", "en", "shopping", "A1"),
("expensive", "дорогой", "en", "shopping", "A1"),
("money", "деньги", "en", "shopping", "A1"),

("cash", "наличные", "en", "shopping", "A1"),
("card", "карта", "en", "shopping", "A1"),
("customer", "клиент", "en", "shopping", "A1"),
("seller", "продавец", "en", "shopping", "A1"),
("bag", "сумка", "en", "shopping", "A1"),
("box", "коробка", "en", "shopping", "A1"),
("size", "размер", "en", "shopping", "A1"),
("small", "маленький", "en", "shopping", "A1"),
("large", "большой", "en", "shopping", "A1"),
("new", "новый", "en", "shopping", "A1"),


# COMMON VERBS A1

("be", "быть", "en", "verbs", "A1"),
("have", "иметь", "en", "verbs", "A1"),
("do", "делать", "en", "verbs", "A1"),
("make", "делать/создавать", "en", "verbs", "A1"),
("get", "получать", "en", "verbs", "A1"),
("give", "давать", "en", "verbs", "A1"),
("take", "брать", "en", "verbs", "A1"),
("see", "видеть", "en", "verbs", "A1"),
("look", "смотреть", "en", "verbs", "A1"),
("know", "знать", "en", "verbs", "A1"),

("think", "думать", "en", "verbs", "A1"),
("want", "хотеть", "en", "verbs", "A1"),
("need", "нуждаться", "en", "verbs", "A1"),
("like", "нравиться", "en", "verbs", "A1"),
("love", "любить", "en", "verbs", "A1"),
("hate", "ненавидеть", "en", "verbs", "A1"),
("find", "находить", "en", "verbs", "A1"),
("use", "использовать", "en", "verbs", "A1"),
("try", "пробовать", "en", "verbs", "A1"),
("ask", "спрашивать", "en", "verbs", "A1"),

("tell", "рассказывать", "en", "verbs", "A1"),
("say", "сказать", "en", "verbs", "A1"),
("speak", "говорить", "en", "verbs", "A1"),
("read", "читать", "en", "verbs", "A1"),
("write", "писать", "en", "verbs", "A1"),
("learn", "учить", "en", "verbs", "A1"),
("teach", "обучать", "en", "verbs", "A1"),
("remember", "помнить", "en", "verbs", "A1"),
("forget", "забывать", "en", "verbs", "A1"),
("understand", "понимать", "en", "verbs", "A1"),
("family", "семья", "en", "family", "A1"),
("father", "отец", "en", "family", "A1"),
("mother", "мать", "en", "family", "A1"),
("parent", "родитель", "en", "family", "A1"),
("son", "сын", "en", "family", "A1"),
("daughter", "дочь", "en", "family", "A1"),
("brother", "брат", "en", "family", "A1"),
("sister", "сестра", "en", "family", "A1"),
("husband", "муж", "en", "family", "A1"),
("wife", "жена", "en", "family", "A1"),

("grandfather", "дедушка", "en", "family", "A1"),
("grandmother", "бабушка", "en", "family", "A1"),
("uncle", "дядя", "en", "family", "A1"),
("aunt", "тётя", "en", "family", "A1"),
("cousin", "двоюродный брат/сестра", "en", "family", "A1"),
("child", "ребёнок", "en", "family", "A1"),
("baby", "малыш", "en", "family", "A1"),
("friend", "друг", "en", "family", "A1"),
("neighbor", "сосед", "en", "family", "A1"),
("people", "люди", "en", "family", "A1"),


# EMOTIONS A1

("happy", "счастливый", "en", "emotions", "A1"),
("sad", "грустный", "en", "emotions", "A1"),
("angry", "злой", "en", "emotions", "A1"),
("afraid", "испуганный", "en", "emotions", "A1"),
("tired", "уставший", "en", "emotions", "A1"),
("excited", "взволнованный", "en", "emotions", "A1"),
("bored", "скучающий", "en", "emotions", "A1"),
("busy", "занятый", "en", "emotions", "A1"),
("calm", "спокойный", "en", "emotions", "A1"),
("worried", "обеспокоенный", "en", "emotions", "A1"),

("love", "любовь", "en", "emotions", "A1"),
("hope", "надежда", "en", "emotions", "A1"),
("fear", "страх", "en", "emotions", "A1"),
("smile", "улыбка", "en", "emotions", "A1"),
("laugh", "смех", "en", "emotions", "A1"),
("cry", "плакать", "en", "emotions", "A1"),
("feel", "чувствовать", "en", "emotions", "A1"),
("like", "нравиться", "en", "emotions", "A1"),
("want", "хотеть", "en", "emotions", "A1"),
("need", "нуждаться", "en", "emotions", "A1"),


# ADJECTIVES A1

("big", "большой", "en", "adjectives", "A1"),
("small", "маленький", "en", "adjectives", "A1"),
("long", "длинный", "en", "adjectives", "A1"),
("short", "короткий", "en", "adjectives", "A1"),
("high", "высокий", "en", "adjectives", "A1"),
("low", "низкий", "en", "adjectives", "A1"),
("good", "хороший", "en", "adjectives", "A1"),
("bad", "плохой", "en", "adjectives", "A1"),
("beautiful", "красивый", "en", "adjectives", "A1"),
("ugly", "некрасивый", "en", "adjectives", "A1"),

("easy", "лёгкий", "en", "adjectives", "A1"),
("difficult", "сложный", "en", "adjectives", "A1"),
("fast", "быстрый", "en", "adjectives", "A1"),
("slow", "медленный", "en", "adjectives", "A1"),
("hot", "горячий", "en", "adjectives", "A1"),
("cold", "холодный", "en", "adjectives", "A1"),
("young", "молодой", "en", "adjectives", "A1"),
("old", "старый", "en", "adjectives", "A1"),
("new", "новый", "en", "adjectives", "A1"),
("clean", "чистый", "en", "adjectives", "A1"),

("dirty", "грязный", "en", "adjectives", "A1"),
("rich", "богатый", "en", "adjectives", "A1"),
("poor", "бедный", "en", "adjectives", "A1"),
("strong", "сильный", "en", "adjectives", "A1"),
("weak", "слабый", "en", "adjectives", "A1"),
("kind", "добрый", "en", "adjectives", "A1"),
("nice", "приятный", "en", "adjectives", "A1"),
("smart", "умный", "en", "adjectives", "A1"),
("funny", "смешной", "en", "adjectives", "A1"),
("important", "важный", "en", "adjectives", "A1"),
("place", "место", "en", "places", "A1"),
("city", "город", "en", "places", "A1"),
("town", "городок", "en", "places", "A1"),
("village", "деревня", "en", "places", "A1"),
("street", "улица", "en", "places", "A1"),
("road", "дорога", "en", "places", "A1"),
("park", "парк", "en", "places", "A1"),
("school", "школа", "en", "places", "A1"),
("hospital", "больница", "en", "places", "A1"),
("bank", "банк", "en", "places", "A1"),

("shop", "магазин", "en", "places", "A1"),
("market", "рынок", "en", "places", "A1"),
("restaurant", "ресторан", "en", "places", "A1"),
("cafe", "кафе", "en", "places", "A1"),
("hotel", "отель", "en", "places", "A1"),
("airport", "аэропорт", "en", "places", "A1"),
("station", "станция", "en", "places", "A1"),
("library", "библиотека", "en", "places", "A1"),
("museum", "музей", "en", "places", "A1"),
("cinema", "кинотеатр", "en", "places", "A1"),


# CITY A1

("building", "здание", "en", "city", "A1"),
("house", "дом", "en", "city", "A1"),
("flat", "квартира", "en", "city", "A1"),
("office", "офис", "en", "city", "A1"),
("factory", "фабрика", "en", "city", "A1"),
("bridge", "мост", "en", "city", "A1"),
("traffic", "движение", "en", "city", "A1"),
("car", "машина", "en", "city", "A1"),
("bus", "автобус", "en", "city", "A1"),
("train", "поезд", "en", "city", "A1"),

("taxi", "такси", "en", "city", "A1"),
("bike", "велосипед", "en", "city", "A1"),
("crossing", "переход", "en", "city", "A1"),
("corner", "угол", "en", "city", "A1"),
("center", "центр", "en", "city", "A1"),
("north", "север", "en", "city", "A1"),
("south", "юг", "en", "city", "A1"),
("east", "восток", "en", "city", "A1"),
("west", "запад", "en", "city", "A1"),
("near", "рядом", "en", "city", "A1"),


# EVERYDAY OBJECTS A1

("thing", "вещь", "en", "objects", "A1"),
("table", "стол", "en", "objects", "A1"),
("chair", "стул", "en", "objects", "A1"),
("bed", "кровать", "en", "objects", "A1"),
("door", "дверь", "en", "objects", "A1"),
("window", "окно", "en", "objects", "A1"),
("wall", "стена", "en", "objects", "A1"),
("floor", "пол", "en", "objects", "A1"),
("lamp", "лампа", "en", "objects", "A1"),
("clock", "часы", "en", "objects", "A1"),

("phone", "телефон", "en", "objects", "A1"),
("computer", "компьютер", "en", "objects", "A1"),
("camera", "камера", "en", "objects", "A1"),
("book", "книга", "en", "objects", "A1"),
("paper", "бумага", "en", "objects", "A1"),
("pen", "ручка", "en", "objects", "A1"),
("key", "ключ", "en", "objects", "A1"),
("bag", "сумка", "en", "objects", "A1"),
("box", "коробка", "en", "objects", "A1"),
("bottle", "бутылка", "en", "objects", "A1"),

("cup", "чашка", "en", "objects", "A1"),
("glass", "стакан", "en", "objects", "A1"),
("plate", "тарелка", "en", "objects", "A1"),
("knife", "нож", "en", "objects", "A1"),
("fork", "вилка", "en", "objects", "A1"),
("spoon", "ложка", "en", "objects", "A1"),
("key", "ключ", "en", "objects", "A1"),
("lock", "замок", "en", "objects", "A1"),
("picture", "картина", "en", "objects", "A1"),
("photo", "фотография", "en", "objects", "A1"),
# FOOD A1

("food", "еда", "en", "food", "A1"),
("meal", "приём пищи", "en", "food", "A1"),
("breakfast", "завтрак", "en", "food", "A1"),
("lunch", "обед", "en", "food", "A1"),
("dinner", "ужин", "en", "food", "A1"),
("bread", "хлеб", "en", "food", "A1"),
("rice", "рис", "en", "food", "A1"),
("pasta", "макароны", "en", "food", "A1"),
("soup", "суп", "en", "food", "A1"),
("meat", "мясо", "en", "food", "A1"),

("chicken", "курица", "en", "food", "A1"),
("beef", "говядина", "en", "food", "A1"),
("fish", "рыба", "en", "food", "A1"),
("egg", "яйцо", "en", "food", "A1"),
("cheese", "сыр", "en", "food", "A1"),
("butter", "масло", "en", "food", "A1"),
("milk", "молоко", "en", "food", "A1"),
("cream", "сливки", "en", "food", "A1"),
("salt", "соль", "en", "food", "A1"),
("sugar", "сахар", "en", "food", "A1"),

("apple", "яблоко", "en", "food", "A1"),
("banana", "банан", "en", "food", "A1"),
("orange", "апельсин", "en", "food", "A1"),
("lemon", "лимон", "en", "food", "A1"),
("grape", "виноград", "en", "food", "A1"),
("pear", "груша", "en", "food", "A1"),
("potato", "картофель", "en", "food", "A1"),
("tomato", "помидор", "en", "food", "A1"),
("carrot", "морковь", "en", "food", "A1"),
("onion", "лук", "en", "food", "A1"),


# DRINKS A1

("drink", "напиток", "en", "drinks", "A1"),
("water", "вода", "en", "drinks", "A1"),
("tea", "чай", "en", "drinks", "A1"),
("coffee", "кофе", "en", "drinks", "A1"),
("juice", "сок", "en", "drinks", "A1"),
("milk", "молоко", "en", "drinks", "A1"),
("cup", "чашка", "en", "drinks", "A1"),
("glass", "стакан", "en", "drinks", "A1"),
("bottle", "бутылка", "en", "drinks", "A1"),
("hot", "горячий", "en", "drinks", "A1"),


# COOKING A1

("cook", "готовить", "en", "cooking", "A1"),
("kitchen", "кухня", "en", "cooking", "A1"),
("knife", "нож", "en", "cooking", "A1"),
("fork", "вилка", "en", "cooking", "A1"),
("spoon", "ложка", "en", "cooking", "A1"),
("plate", "тарелка", "en", "cooking", "A1"),
("bowl", "миска", "en", "cooking", "A1"),
("pan", "сковорода", "en", "cooking", "A1"),
("pot", "кастрюля", "en", "cooking", "A1"),
("oven", "духовка", "en", "cooking", "A1"),

("wash", "мыть", "en", "cooking", "A1"),
("cut", "резать", "en", "cooking", "A1"),
("mix", "смешивать", "en", "cooking", "A1"),
("boil", "варить", "en", "cooking", "A1"),
("fry", "жарить", "en", "cooking", "A1"),
("taste", "пробовать вкус", "en", "cooking", "A1"),
("eat", "есть", "en", "cooking", "A1"),
("drink", "пить", "en", "cooking", "A1"),
("hungry", "голодный", "en", "cooking", "A1"),
("thirsty", "хотеть пить", "en", "cooking", "A1"),


# RESTAURANT A1

("restaurant", "ресторан", "en", "restaurant", "A1"),
("menu", "меню", "en", "restaurant", "A1"),
("order", "заказ", "en", "restaurant", "A1"),
("waiter", "официант", "en", "restaurant", "A1"),
("customer", "клиент", "en", "restaurant", "A1"),
("table", "стол", "en", "restaurant", "A1"),
("bill", "счёт", "en", "restaurant", "A1"),
("price", "цена", "en", "restaurant", "A1"),
("pay", "платить", "en", "restaurant", "A1"),
("tip", "чаевые", "en", "restaurant", "A1"),
# PRONOUNS A1

("I", "я", "en", "pronouns", "A1"),
("you", "ты/вы", "en", "pronouns", "A1"),
("he", "он", "en", "pronouns", "A1"),
("she", "она", "en", "pronouns", "A1"),
("it", "это/оно", "en", "pronouns", "A1"),
("we", "мы", "en", "pronouns", "A1"),
("they", "они", "en", "pronouns", "A1"),

("my", "мой", "en", "pronouns", "A1"),
("your", "твой/ваш", "en", "pronouns", "A1"),
("his", "его", "en", "pronouns", "A1"),
("her", "её", "en", "pronouns", "A1"),
("our", "наш", "en", "pronouns", "A1"),
("their", "их", "en", "pronouns", "A1"),

("this", "это", "en", "pronouns", "A1"),
("that", "то", "en", "pronouns", "A1"),
("these", "эти", "en", "pronouns", "A1"),
("those", "те", "en", "pronouns", "A1"),


# QUESTION WORDS A1

("what", "что", "en", "questions", "A1"),
("who", "кто", "en", "questions", "A1"),
("where", "где", "en", "questions", "A1"),
("when", "когда", "en", "questions", "A1"),
("why", "почему", "en", "questions", "A1"),
("how", "как", "en", "questions", "A1"),
("which", "какой", "en", "questions", "A1"),
("whose", "чей", "en", "questions", "A1"),


# PREPOSITIONS A1

("in", "в", "en", "prepositions", "A1"),
("on", "на", "en", "prepositions", "A1"),
("at", "у/в", "en", "prepositions", "A1"),
("to", "к/в", "en", "prepositions", "A1"),
("from", "из/от", "en", "prepositions", "A1"),
("with", "с", "en", "prepositions", "A1"),
("without", "без", "en", "prepositions", "A1"),
("for", "для", "en", "prepositions", "A1"),
("about", "о/об", "en", "prepositions", "A1"),
("under", "под", "en", "prepositions", "A1"),

("over", "над", "en", "prepositions", "A1"),
("between", "между", "en", "prepositions", "A1"),
("near", "рядом", "en", "prepositions", "A1"),
("behind", "позади", "en", "prepositions", "A1"),
("front", "перед", "en", "prepositions", "A1"),


# BASIC PHRASES A1

("hello", "привет", "en", "phrases", "A1"),
("hi", "привет", "en", "phrases", "A1"),
("goodbye", "до свидания", "en", "phrases", "A1"),
("please", "пожалуйста", "en", "phrases", "A1"),
("thanks", "спасибо", "en", "phrases", "A1"),
("sorry", "извините", "en", "phrases", "A1"),
("yes", "да", "en", "phrases", "A1"),
("no", "нет", "en", "phrases", "A1"),
("okay", "хорошо", "en", "phrases", "A1"),
("welcome", "добро пожаловать", "en", "phrases", "A1"),

("good morning", "доброе утро", "en", "phrases", "A1"),
("good night", "спокойной ночи", "en", "phrases", "A1"),
("see you", "увидимся", "en", "phrases", "A1"),
("my name is", "меня зовут", "en", "phrases", "A1"),
("how are you", "как дела", "en", "phrases", "A1"),
("I am fine", "у меня всё хорошо", "en", "phrases", "A1"),
("I don't know", "я не знаю", "en", "phrases", "A1"),
("I understand", "я понимаю", "en", "phrases", "A1"),
("I need help", "мне нужна помощь", "en", "phrases", "A1"),
("thank you", "спасибо", "en", "phrases", "A1"),
# TIME A1

("time", "время", "en", "time", "A1"),
("day", "день", "en", "time", "A1"),
("week", "неделя", "en", "time", "A1"),
("month", "месяц", "en", "time", "A1"),
("year", "год", "en", "time", "A1"),
("today", "сегодня", "en", "time", "A1"),
("tomorrow", "завтра", "en", "time", "A1"),
("yesterday", "вчера", "en", "time", "A1"),
("morning", "утро", "en", "time", "A1"),
("evening", "вечер", "en", "time", "A1"),

("night", "ночь", "en", "time", "A1"),
("hour", "час", "en", "time", "A1"),
("minute", "минута", "en", "time", "A1"),
("second", "секунда", "en", "time", "A1"),
("early", "рано", "en", "time", "A1"),
("late", "поздно", "en", "time", "A1"),


# COLORS A1

("color", "цвет", "en", "colors", "A1"),
("red", "красный", "en", "colors", "A1"),
("blue", "синий", "en", "colors", "A1"),
("green", "зелёный", "en", "colors", "A1"),
("yellow", "жёлтый", "en", "colors", "A1"),
("black", "чёрный", "en", "colors", "A1"),
("white", "белый", "en", "colors", "A1"),
("brown", "коричневый", "en", "colors", "A1"),
("orange", "оранжевый", "en", "colors", "A1"),
("pink", "розовый", "en", "colors", "A1"),


# BODY A1

("body", "тело", "en", "body", "A1"),
("head", "голова", "en", "body", "A1"),
("face", "лицо", "en", "body", "A1"),
("eye", "глаз", "en", "body", "A1"),
("ear", "ухо", "en", "body", "A1"),
("nose", "нос", "en", "body", "A1"),
("mouth", "рот", "en", "body", "A1"),
("hand", "рука", "en", "body", "A1"),
("arm", "рука", "en", "body", "A1"),
("leg", "нога", "en", "body", "A1"),

("foot", "ступня", "en", "body", "A1"),
("finger", "палец", "en", "body", "A1"),
("hair", "волосы", "en", "body", "A1"),
("heart", "сердце", "en", "body", "A1"),
("blood", "кровь", "en", "body", "A1"),


# CLOTHES A1

("clothes", "одежда", "en", "clothes", "A1"),
("shirt", "рубашка", "en", "clothes", "A1"),
("t-shirt", "футболка", "en", "clothes", "A1"),
("pants", "брюки", "en", "clothes", "A1"),
("jeans", "джинсы", "en", "clothes", "A1"),
("dress", "платье", "en", "clothes", "A1"),
("skirt", "юбка", "en", "clothes", "A1"),
("coat", "пальто", "en", "clothes", "A1"),
("jacket", "куртка", "en", "clothes", "A1"),
("shoe", "ботинок", "en", "clothes", "A1"),

("sock", "носок", "en", "clothes", "A1"),
("hat", "шапка", "en", "clothes", "A1"),
("glove", "перчатка", "en", "clothes", "A1"),


# WEATHER A1

("weather", "погода", "en", "weather", "A1"),
("sun", "солнце", "en", "weather", "A1"),
("rain", "дождь", "en", "weather", "A1"),
("snow", "снег", "en", "weather", "A1"),
("wind", "ветер", "en", "weather", "A1"),
("cloud", "облако", "en", "weather", "A1"),
("sky", "небо", "en", "weather", "A1"),
("hot", "жарко", "en", "weather", "A1"),
("cold", "холодно", "en", "weather", "A1"),
("warm", "тепло", "en", "weather", "A1"),


# COMMON ACTIONS A1

("go", "идти", "en", "verbs", "A1"),
("come", "приходить", "en", "verbs", "A1"),
("see", "видеть", "en", "verbs", "A1"),
("look", "смотреть", "en", "verbs", "A1"),
("hear", "слышать", "en", "verbs", "A1"),
("say", "говорить", "en", "verbs", "A1"),
("tell", "рассказывать", "en", "verbs", "A1"),
("make", "делать", "en", "verbs", "A1"),
("do", "делать", "en", "verbs", "A1"),
("take", "брать", "en", "verbs", "A1"),

("give", "давать", "en", "verbs", "A1"),
("get", "получать", "en", "verbs", "A1"),
("put", "класть", "en", "verbs", "A1"),
("find", "находить", "en", "verbs", "A1"),
("open", "открывать", "en", "verbs", "A1"),
("close", "закрывать", "en", "verbs", "A1"),
("read", "читать", "en", "verbs", "A1"),
("write", "писать", "en", "verbs", "A1"),
("learn", "учить", "en", "verbs", "A1"),
("speak", "говорить", "en", "verbs", "A1"),
]

async def add_words():

    await db.connect_db()

    for word in WORDS:

        await db.pool.execute(
            """
            INSERT INTO words
            (
                word,
                translation,
                language,
                category,
                level
            )
            VALUES
            ($1,$2,$3,$4,$5)

            ON CONFLICT(word, translation, language)
            DO NOTHING
            """,
            *word
        )

    count = await db.pool.fetchval(
        "SELECT COUNT(*) FROM words"
    )

    print("Всего слов в базе:", count)

    
    print("A1 слова добавлены:",len(WORDS))


asyncio.run(add_words())